export enum Categories {
  VEGETABLES = "VEGETABLES",
  FRUITS = "FRUITS",
  DAIRY = "DAIRY",
  MEAT = "MEAT",
  FISH = "FISH",
  GRAIN_PRODUCTS = "GRAIN_PRODUCTS",
  PROCESSED_FOODS = "PROCESSED_FOODS",
}
