import {
  AccountStatistics,
  CreateAddressMZWO,
  CreateAnnouncementMZWO,
  CreateEventMZWO,
  CreateProductMZWO,
  FilterFormData,
} from "../type/mzwo";

export const initialAddress: CreateAddressMZWO = {
  city: "",
  street: "",
  streetNumber: "",
  postalCode: "",
  latitude: "",
  longitude: "",
};

export const initialProduct: CreateProductMZWO = {
  productName: "",
  category: "",
  image: "",
};

export const initialEvent: CreateEventMZWO = {
  title: "",
  content: "",
  startDate: "",
  endDate: "",
  location: initialAddress,
  product: initialProduct,
  foodUnit: "",
  foodQuantity: 1,
  maxParticipants: 1,
  maxReservationQuantity: 1,
};

export const initialAnnouncement: CreateAnnouncementMZWO = {
  title: "",
  content: "",
};

export const initialEventFilters: FilterFormData = {
  searchString: "",
  city: "",
  street: "",
  eventFilter: "",
  eventState: "",
  productCategory: "",
  startDate: "",
  endDate: "",
};

export const initialAccountStatistics: AccountStatistics = {
  eventsCreated: 0,
  announcementsPublished: 0,
  reservationsMade: 0,
  reservationsByParticipants: 0,
  eventsAttended: 0,
  averageEventParticipants: 0.0,
  totalEventsParticipants: 0,
  mostCommonCategory: "---",
  yourClaimedFood: {
    Proteins: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Prepared: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Grain: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Vegetables: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Dairy: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Beverages: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Sweets: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Fruits: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
  },
  averageEventFoodGiven: {
    Proteins: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Prepared: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Grain: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Vegetables: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Dairy: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Beverages: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Sweets: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Fruits: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
  },
  totalFoodClaimed: {
    Proteins: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Prepared: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Grain: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Vegetables: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Dairy: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Beverages: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Sweets: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Fruits: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
  },
  totalEventFood: {
    Proteins: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Prepared: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Grain: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Vegetables: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Dairy: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Beverages: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Sweets: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
    Fruits: {
      Item: 0.0,
      Liter: 0.0,
      Piece: 0.0,
      Kilogram: 0.0,
      Pack: 0.0,
    },
  },
};
