export const CLIENT_USER = "CLIENT_USER";
export const CLIENT_VOLUNTEER = "CLIENT_VOLUNTEER";
export const CLIENT_MANAGER = "CLIENT_MANAGER";
export const CLIENT_MODERATOR = "CLIENT_MODERATOR";
export const CLIENT_ADMIN = "CLIENT_ADMIN";
export const CLIENT_GUEST = "CLIENT_GUEST";
